stages:
  - test
  - build
  - deploy

clazy:
  stage: test
  image: kaidan/neon-bionic
  variables:
    CMAKE_CXX_COMPILER: clazy
  script: utils/travis/build.sh

qmllint:
  stage: test
  image: kaidan/neon-bionic
  script: qmllint $(find . -name "*.qml")
  variables:
    QT_SELECT: 5

ubuntu-trusty:
  stage: build
  image: kaidan/ubuntu-trusty
  script: utils/travis/build.sh

neon-bionic:
  stage: build
  image: kaidan/neon-bionic
  script: utils/travis/build.sh

debian-sid:
  stage: build
  image: kaidan/debian-unstable
  script: utils/travis/build.sh

archlinux:
  stage: build
  image: kaidan/archlinux
  script: utils/travis/build.sh

linux-appimage:
  stage: deploy
  image: kaidan/ubuntu-trusty
  script: utils/build-linux-appimage.sh
  variables:
    QXMPP_BUILD: /usr
  allow_failure: true
  artifacts:
    paths:
      - "*.AppImage"
      - "*.AppImage.zsync"
    expire_in: 1 week

click-xenial:
  stage: deploy
  image: kaidan/ubuntu-touch-xenial
  script: utils/travis/build.sh
  variables:
    PLATFORM: ubuntu-touch
  artifacts:
    paths:
      - "*.click"
    expire_in: 1 week

windows-mxe:
  stage: deploy
  image: kaidan/windows-mxe
  script:
    - utils/build-windows-mxe.sh
    - mv build/bin/kaidan.exe kaidan.exe
  artifacts:
    paths:
      - "kaidan.exe"
    expire_in: 1 week

android:
  stage: deploy
  image: kdeorg/android-sdk
  script:
    - sudo apt -y install inkscape optipng
    - GIT_EXTRA="--branch ${KF5_VERSION}" /opt/helpers/build-kde-dependencies --withProject kirigami
    - /opt/helpers/build-cmake qxmpp https://github.com/qxmpp-project/qxmpp.git -DBUILD_EXAMPLES=OFF -DBUILD_TESTS=OFF
    - GIT_EXTRA="--branch ${CI_COMMIT_REF_NAME} --recursive" /opt/helpers/build-cmake ${CI_PROJECT_NAME} ${CI_REPOSITORY_URL} -DQTANDROID_EXPORTED_TARGET=kaidan -DANDROID_APK_DIR=${CI_PROJECT_DIR}/src/${CI_PROJECT_NAME}/misc/android -DI18N=1
    - ${CI_PROJECT_DIR}/src/${CI_PROJECT_NAME}/utils/render-logos.sh
    - /opt/helpers/create-apk ${CI_PROJECT_NAME}
    - mv ${CI_PROJECT_DIR}/build/${CI_PROJECT_NAME}/kaidan_build_apk/build/outputs/apk/kaidan_build_apk-debug.apk ${CI_PROJECT_DIR}
  variables:
    KF5_VERSION: master
  artifacts:
    paths:
      - "kaidan_build_apk-debug.apk"
    expire_in: 1 week


variables:
  GIT_SUBMODULE_STRATEGY: recursive
  BUILD_SYSTEM: cmake
  BUILD_TYPE: Release
